name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run:  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Run NVM
        run: export NVM_DIR="$HOME/ .nvm" && . "$NVM_DIR/nvm.sh" --no-use
      - name: Install Node.js
        env:
          NODE_VERSION: 14.17.9   
        run: nvm install
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint
